# 퍼셉트론(perceptron)

## 1. 단층 퍼셉트론

In [1]:
# 경고 무시
from warnings import filterwarnings
filterwarnings("ignore")

### 1) 단층 퍼셉트론으로 OR 게이트 구현

|x1|x2|y|
|---|---|---|
|0|0|0|
|1|0|1|
|0|1|1|
|1|1|1|

In [11]:
# 단층 퍼셉트론으로 OR 게이트 구현
import tensorflow as tf
import numpy as np

from keras.models import Sequential
from keras.layers import Dense # 연결층
from keras.optimizers import SGD # 경사하강법
from keras.losses import mse # 오차를 줄이는 방법

tf.random.set_seed(0)

# 데이터 준비
data = np.array([[0, 0], [1, 0], [0, 1], [1, 1]]) # 입력 X
label = np.array([[0], [1], [1], [1]]) # 출력 Y

# 모델 구성 - 단층 퍼셉트론 구성 _ 단층퍼셉트론: 한층만 가져오기 때문에 은닉층이 없음.
model = Sequential()
model.add(Dense(1, input_shape = (2, ), activation = 'linear'))  # 단층, 입력이 두개, 결과값 그대로 준다.

# 컴파일 설정
model.compile(optimizer = SGD(), loss = mse, metrics = ['acc']) 

# 모델 학습
model.fit(data, label, epochs = 500) # 500번 반복

Epoch 1/500
1/1 [==============================] - 1s 701ms/step - loss: 0.6436 - acc: 0.2500
Epoch 2/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6107 - acc: 0.2500
Epoch 3/500
1/1 [==============================] - 0s 13ms/step - loss: 0.5798 - acc: 0.2500
Epoch 4/500
1/1 [==============================] - 0s 31ms/step - loss: 0.5509 - acc: 0.2500
Epoch 5/500
1/1 [==============================] - 0s 17ms/step - loss: 0.5237 - acc: 0.2500
Epoch 6/500
1/1 [==============================] - 0s 9ms/step - loss: 0.4982 - acc: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 18ms/step - loss: 0.4742 - acc: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 11ms/step - loss: 0.4518 - acc: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 0.4307 - acc: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 11ms/step - loss: 0.4109 - acc: 0.5000
Epoch 11/500
1/1 [==============================] - 0s 11ms/step - loss

In [13]:
# 모델 가중치(w), 편향(b) 확인하기
model.get_weights() # 2개의 가중치, 1개의 편향(bias)

"""
        [array([[0.49410528], # w1
                [0.44091424]], dtype=float32), # w2
        array([0.28853792], dtype=float32)] # bias
"""

[array([[0.49410528],
        [0.44091424]], dtype=float32),
 array([0.28853792], dtype=float32)]

In [15]:
# 모델 평가
model.evaluate(data, label)

1/1 [==============================] - 0s 28ms/step - loss: 0.0634 - acc: 1.0000


[0.06341804563999176, 1.0]

In [16]:
# 모델 예측
result = model.predict(data)
print(result)

"""
# 0.5 보다 크면 1 작으면 0
[[0.28853792] # 0
 [0.7826432 ] # 1
 [0.72945213] # 1
 [1.2235575 ]] # 1
"""

1/1 [==============================] - 0s 96ms/step
[[0.28853792]
 [0.7826432 ]
 [0.72945213]
 [1.2235575 ]]


### 2) 단층 퍼셉트론으로 AND 게이트 구현

|x1|x2|y|
|---|---|---|
|0|0|0|
|1|0|0|
|0|1|0|
|1|1|1|

In [17]:
# 단층 퍼셉트론으로 AND 게이트 구현
import tensorflow as tf
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from keras.losses import mse

tf.random.set_seed(0)

# 데이터 준비
data = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
label = np.array([[0], [0], [0], [1]])

# 모델 구성- 단층 퍼셉트론 구성
model = Sequential()
model.add(Dense(1, input_shape = (2, ), activation = 'linear')) 

# 컴파일 설정
model.compile(optimizer = SGD(), loss = mse, metrics = ['acc']) 

# 모델 학습
model.fit(data, label, epochs = 500)

Epoch 1/500
1/1 [==============================] - 0s 425ms/step - loss: 0.5724 - acc: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 12ms/step - loss: 0.5421 - acc: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 26ms/step - loss: 0.5136 - acc: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 15ms/step - loss: 0.4870 - acc: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 17ms/step - loss: 0.4620 - acc: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 14ms/step - loss: 0.4385 - acc: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 16ms/step - loss: 0.4166 - acc: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 15ms/step - loss: 0.3959 - acc: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3766 - acc: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 7ms/step - loss: 0.3584 - acc: 0.5000
Epoch 11/500
1/1 [==============================] - 0s 18ms/step - los

In [18]:
# 모델 가중치(w), 편향(b) 확인
model.get_weights() # 2개의 가중치, 1개의 편향(bias)

[array([[0.5459933],
        [0.5136099]], dtype=float32),
 array([-0.28534865], dtype=float32)]

In [19]:
# 모델 평가
model.evaluate(data, label)

1/1 [==============================] - 0s 134ms/step - loss: 0.0631 - acc: 1.0000


[0.06310592591762543, 1.0]

In [8]:
# 모델 예측
result = model.predict(data)
print(result)
"""
[[-0.14440186]  # 0
 [ 0.34790927]  # 0
 [ 0.18523358]  # 0
 [ 0.6775447 ]] # 1
"""

1/1 [==============================] - 0s 68ms/step
[[-0.14440186]
 [ 0.34790927]
 [ 0.18523358]
 [ 0.6775447 ]]


### 3) 단층 퍼셉트론으로 XOR 게이트 구현 --> `실패`
- 500번 에폭으로 학습 진행 -> 모델은 학습되지 않음 -> 실패
- 10000번의 에폭으로 학습 진행 -> 모델은 학습되지 않음 -> 실패
- 한 개의 직선을 이용해서는 XOR 문제를 해결할 수 없음 -> 다중 퍼셉트론(MLP; Multi-Layer Perceptron) 등장

#### (1) 에폭 500번으로 모델 학습

In [20]:
# 단층 퍼셉트론으로 XOR 게이트 구현
import tensorflow as tf
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from keras.losses import mse

tf.random.set_seed(0)

# 데이터 준비
data = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
label = np.array([[0], [1], [1], [0]])

# 모델 구성하
model = Sequential()
model.add(Dense(1, input_shape = (2, ), activation = 'linear'))

# 컴파일 설정
model.compile(optimizer = SGD(), loss = mse, metrics = ['acc'])

# 모델 학습
model.fit(data, label, epochs = 500)

Epoch 1/500
1/1 [==============================] - 0s 379ms/step - loss: 0.3923 - acc: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3881 - acc: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 20ms/step - loss: 0.3841 - acc: 0.7500
Epoch 4/500
1/1 [==============================] - 0s 40ms/step - loss: 0.3804 - acc: 0.7500
Epoch 5/500
1/1 [==============================] - 0s 15ms/step - loss: 0.3768 - acc: 0.7500
Epoch 6/500
1/1 [==============================] - 0s 13ms/step - loss: 0.3735 - acc: 0.7500
Epoch 7/500
1/1 [==============================] - 0s 20ms/step - loss: 0.3703 - acc: 0.7500
Epoch 8/500
1/1 [==============================] - 0s 113ms/step - loss: 0.3673 - acc: 0.7500
Epoch 9/500
1/1 [==============================] - 0s 10ms/step - loss: 0.3644 - acc: 0.7500
Epoch 10/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3617 - acc: 0.5000
Epoch 11/500
1/1 [==============================] - 0s 19ms/step - lo

#### (2) 에폭 10000번으로 모델 학습

In [ ]:
# 단층 퍼셉트론으로 XOR 게이트 구현
import tensorflow as tf
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from keras.losses import mse

tf.random.set_seed(0)

# 데이터 준비
data = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
label = np.array([[0], [1], [1], [0]])

# 모델 구성하
model = Sequential()
model.add(Dense(1, input_shape = (2, ), activation = 'linear'))

# 컴파일 설정
model.compile(optimizer = SGD(), loss = mse, metrics = ['acc'])

# 모델 학습
model.fit(data, label, epochs = 1000)

## 2. 다층 퍼셉트론

### 1) 다층 퍼셉트론을 이용하여 XOR 게이트 구현
- Dense층에 32개의 노드(퍼셉트론) 사용
- 비선형 활성화 함수 사용, activation='relu'
- 최적화 함수, optimizer = Adam()

In [21]:
# 다층 퍼셉트론을 이용하여 XOR 게이트 구현
import tensorflow as tf
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras.losses import mse

tf.random.set_seed(0)

# 데이터 준비
data = np.array([[0, 0], [1, 0], [0, 1], [1, 1]]) # X
label = np.array([[0], [1], [1], [0]]) # Y

# 모델 구성
model = Sequential()
model.add(Dense(32, input_shape = (2, ), activation = 'relu'))  # 32개의 노드(퍼셉트론) 사용
model.add(Dense(1, activation = 'sigmoid'))

# 컴파일 설정
model.compile(optimizer = Adam(), loss = mse, metrics = ['acc'])

# 모델 학습
model.fit(data, label, epochs = 500)

Epoch 1/500
1/1 [==============================] - 1s 526ms/step - loss: 0.2475 - acc: 0.7500
Epoch 2/500
1/1 [==============================] - 0s 12ms/step - loss: 0.2471 - acc: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 16ms/step - loss: 0.2466 - acc: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 11ms/step - loss: 0.2462 - acc: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 20ms/step - loss: 0.2457 - acc: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 27ms/step - loss: 0.2453 - acc: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 10ms/step - loss: 0.2449 - acc: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 19ms/step - loss: 0.2445 - acc: 0.7500
Epoch 9/500
1/1 [==============================] - 0s 24ms/step - loss: 0.2441 - acc: 0.7500
Epoch 10/500
1/1 [==============================] - 0s 16ms/step - loss: 0.2437 - acc: 0.7500
Epoch 11/500
1/1 [==============================] - 0s 12ms/step - l

In [22]:
# 모델 평가
model.evaluate(data, label)

1/1 [==============================] - 0s 120ms/step - loss: 0.0429 - acc: 1.0000


[0.04287371411919594, 1.0]

In [23]:
# 모델 예측
result = model.predict(data)
print(result)

1/1 [==============================] - 0s 47ms/step
[[0.23743902]
 [0.8036921 ]
 [0.80399615]
 [0.19535418]]
