# Tensor
> 배열(Array)나 행렬(Matrix)과 유사한 자료 구조.

## 텐서 생성

- `torch.tensor()` : 입력된 데이터를 복사해서(값이 무조건 필요) 텐서로 변환한다.
- (권장) `torch.Tensor()` : 'Tensor'의 기본형, 텐서 인스턴스를 생성하는 클래스이다.(값이 없는 경우, 비어있는 텐서 생성)

In [3]:
import torch

print(torch.tensor([0, 1, 2]))
print(torch.Tensor([[0, 1, 2],[3, 4, 5]]))
print(torch.IntTensor([0, 1, 2]))
print(torch.LongTensor([0, 1, 2]))
print(torch.FloatTensor([0., 1., 2.]))

tensor([0, 1, 2])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([0, 1, 2], dtype=torch.int32)
tensor([0, 1, 2])
tensor([0., 1., 2.])


## Tensor Attribute

- `형태(shape)`: 텐서의 차원
- `자료형(dtype)`: 텐서에 할당된 데이터 형식
- `장치(device)`: GPU 가속 여부

## 차원 변환

- `reshape`: 텐서의 차원 변환

In [17]:
tensor = torch.rand(1,2) # rand: 0과 1사이의 무작위 숫자를 균등 분포로 생성, 여기서 (1,2)는 생성하려는 텐서의 형태를 의미한다.
print(f'tensor: {tensor}, shape: {tensor.shape}')

retensor = tensor.reshape(2,1)
print(f'tensor: {retensor}, shape: {retensor.shape}')

tensor: tensor([[0.7993, 0.2064]]), shape: torch.Size([1, 2])
tensor: tensor([[0.7993],
        [0.2064]]), shape: torch.Size([2, 1])


## 자료형 설정(dtype)
> `torch.*` 형태로 할당

In [22]:
tensor = torch.rand((1,2), dtype=torch.float64)
print(tensor)

tensor([[0.4341, 0.6366]], dtype=torch.float64)


## 장치 설정 및 장치 할당
> 현재 맥북 M2 사용 (MPS)

In [27]:
device = "mps" if torch.backends.mps.is_available() else "cpu"

gpu_tensor = torch.rand((1,1), device=device)
print(gpu_tensor)

# 장치 변환
cpu_t = torch.FloatTensor([0, 1, 2])
print(cpu_t.device)
cpu_t = cpu_t.to(device)
print(cpu_t.device)

tensor([[0.4312]], device='mps:0')
cpu
mps:0
